name: Testing - Stop Dev Environment

permissions:
    id-token: write
    contents: read

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 20 * * *'  # 01::00 AM Israel time

jobs:
  Stop-Environment:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Configure Twingate
        uses: twingate/github-action@v1
        with:
          service-key: ${{ secrets.TWINGATE_SERVICE_KEY_SECRET_NAME }}

      - name: Execute EKS Stop Action
        uses: ./.github/actions/stop-dev
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-role: ${{ secrets.AWS_ASSUME_ROLE }}
          eks-cluster: ${{ secrets.EKS_CLUSTER_NAME }}
          environment-name: 'dev'