export * from './arrow-right';
export * from './cards';
export * from './caret-down';
export * from './feed';
export * from './github';
export * from './home';
export * from './insights';
export * from './language';
export * from './rate';
export * from './settings';
export * from './share';
// export * from './style';
export * from './mastercard';
export * from './support';
export * from './transfer';
export * from './visa';
export * from './website';
