spring:
  application:
    name: Banking Integration

server:
  port: 8003

logging:
  level:
    org.springframework.web.client.RestTemplate: DEBUG


midaz:
  url: http://127.0.0.1:3000
  page_size: 10
  page_number: 1
  organization_id: 0196b308-2cfd-74ec-9528-8e9a8834e329
  ledger_id: 0196b30a-20e1-79be-8d3f-59c746f41461
  account:
    get_list_accounts:
      path: /v1/organizations/{organizationId}/ledgers/{ledgerId}/accounts


vietqr:
    url_gen_qr: https://api.vietqr.io/v2/generate
    client_id: c2127e24-dd81-4fdd-9a9b-16fad3ed76af
    api_key: d4277711-6c12-4cab-8fd7-f1cdf3a26d03
