version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: auth
      POSTGRES_PASSWORD: yourpassword
    ports:
      - "5432:5432"

  redis:
    image: redis:6
    ports:
      - "6379:6379"